"""Check every local theorem's kernel dependencies; preserve a reproducible log."""

import hashlib
import json
import re
import subprocess
from pathlib import Path


def main():
    files = sorted(Path("formal/Mamba4").glob("*.lean"))
    declarations = []
    for path in files:
        source = path.read_text()
        assert not re.search(
            r"\b(sorry|admit|native_decide)\b|^\s*axiom\s", source, re.M
        ), path
        prefix = "Mamba4.AffineSummary" if path.stem == "Scan" else "Mamba4"
        names = re.findall(r"^theorem\s+(\w+)", source, re.M)
        declarations += [f"{prefix}.{name}" for name in names]
    assert len(declarations) >= 50, "Expected the complete substantive theorem set"
    verify = Path("formal/Verify.lean")
    verify.write_text(
        "import Mamba4\n\n/-! Generated by scripts/audit_formal.py. -/\n"
        + "\n".join(f"#print axioms {name}" for name in declarations)
        + "\n"
    )
    checked = subprocess.run(
        ["lake", "env", "lean", str(verify)], text=True, capture_output=True, check=True
    )
    output = checked.stdout + checked.stderr
    assert "sorryAx" not in output and "trustCompiler" not in output
    dependencies = set()
    for match in re.finditer(r"depends on axioms:\s*\[([^\]]*)\]", output):
        dependencies.update(x.strip() for x in match[1].split(",") if x.strip())
    allowed = {"propext", "Classical.choice", "Quot.sound"}
    assert dependencies <= allowed, dependencies - allowed
    for name in declarations:
        assert f"'{name}'" in output, f"Missing kernel audit for {name}"
    out = Path("analysis/results")
    out.mkdir(parents=True, exist_ok=True)
    (out / "formal-axioms.txt").write_text(output)
    files += [
        Path("formal/Mamba4.lean"),
        verify,
        Path("lakefile.toml"),
        Path("lean-toolchain"),
        Path("lake-manifest.json"),
    ]
    evidence = {
        "theorem_count": len(declarations),
        "modules": len(list(Path("formal/Mamba4").glob("*.lean"))),
        "declarations": declarations,
        "kernel_dependencies": sorted(dependencies),
        "new_axioms": [],
        "lean_version": subprocess.check_output(
            ["lake", "env", "lean", "--version"], text=True
        ).strip(),
        "source_sha256": {
            str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in files
        },
        "log_sha256": hashlib.sha256(output.encode()).hexdigest(),
    }
    (out / "formal-audit.json").write_text(json.dumps(evidence, indent=2) + "\n")
    print(
        f"Kernel checked {len(declarations)} theorems across {evidence['modules']} modules; only standard Lean axioms."
    )


if __name__ == "__main__":
    main()
